Feature/kotlin insight client sdk
linked-planet/kotlin-atlassian-client pull request #1
Opened 2023-04-12 15:24 UTC by HighKo

2023-05-16 09:28 UTC, sjahreis requested changes

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/error/InsightClientError.kt
Maybe align to other messages? See `AtlasHttpClient`:
```Jira/Insight hat ein internes Problem festgestellt```

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/interfaces/GenericInsightObjectOperator.kt
> +interface GenericInsightObjectOperator<DomainType> {
Please add comments to public api

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/HttpInsightAttachmentOperator.kt
> +            .map { }
Add comment explaining empty map: `/*to Unit*/`

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/HttpInsightObjectOperator.kt
>          // TODO: ensure object type has the specified attributes
Todo still relevant?

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/HttpInsightObjectOperator.kt
>          val objectSelf = "${context.baseUrl}/secure/insight/assets/${this.objectKey}"
Ensure we have a test which tests that the self link works is callable (returns 200)

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/model/InsightObjectExtensions.kt
We should ensure that those methods are tested properly, maybe with dedicated unit tests?

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/model/InsightObjectRestApiResponseObjects.kt
> +    val id: Int, // id 3, name = "Reference"; prefer an ENUM
Change comment to point to `ReferenceKind` for more details

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/model/InsightObjectTypeRestApiResponseObjects.kt
> +    val type: Int // AttributeType 0=Default 1=Reference
Change comment to point to ReferenceKind for more details

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/model/InsightObjectTypeRestApiResponseObjects.kt
> +    // hidden: Boolean
Remove

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/pom.xml
> +<!--        </dependency>-->
Remove

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightAttachmentOperator.kt
> +    ): Either<InsightClientError, List<InsightAttachment>> =
Why do we return a list of attachments?

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightAttachmentOperator.kt
> +        val humanReadableFileSize = humanReadableByteCountSI(fileSize)
Consider using `org.apache.commons.io.FileUtils.byteCountToDisplaySize(fileSize)`

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/HttpInsightObjectOperator.kt
> -        pageFrom: Int,
We should add the possibility to retrieve all objects for an iql without pagination. Let's discuss this one.

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectOperator.kt
> +            val objectTypeBean = objectTypeFacade.loadObjectType(objectTypeId.raw)
`objectTypeFacade.loadObjectType` is called twice, here and in `createEmptyDomainObject`, maybe we can pass the `objectTypeBean` on to the latter method.

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectOperator.kt
> +    private fun setAttributesForObjectBean(
Please move down in private section

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectOperator.kt
> +        val objectSelf = "${baseUrl}/secure/insight/assets/${objectBean.objectKey}"
Is there no `self` attribute?

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectOperator.kt
> +    private suspend fun createInsightObject(
maybe call this one `mapBeansToInsightObject`

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectOperator.kt
> +    private suspend fun createInsightAttribute(
maybe call this one `mapBeansToInsigtAttribute`

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/model/HttpEditModel.kt
> +            if (insightAttr.attributeType == InsightObjectAttributeType.REFERENCE) {
Mapping for `InsightObjectAttributeType.USER` missing

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectTypeOperator.kt
> +    private fun mapDefaultType(defaultType: ObjectTypeAttributeBean.DefaultType) =
Please add return type explicitly

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/services/ReverseEngineeredAttachmentUrlResolver.kt
> +internal class ReverseEngineeredAttachmentUrlResolver {
Just add a small comment why that's necessary and where the sources can be found

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/services/ReverseEngineeredFileManager.kt
> +internal class ReverseEngineeredFileManager{
Just add a small comment why that's necessary and where the sources can be found

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-applink/pom.xml
> +            <version>2.0.3</version>
Extract that version and all its' occurrences as var into the root project

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-applink/src/test/kotlin/it/InsightApplinkClientTest.kt
>          println("### Starting InsightApplinkClientTest")
Started InsightApplinkClientTest - please align this logs in all test modules

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-base/src/main/kotlin/com/linkedplanet/kotlininsightclient/InsightAttachmentOperatorTest.kt
>          println("### START attachment_testGetAndDownloadAttachments")
Correct output - Check logs for all methods!

Is there an automated approach to print such logs?

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-base/src/main/kotlin/com/linkedplanet/kotlininsightclient/InsightHistoryOperatorTest.kt
> +            assertTrue(history.historyItems.isNotEmpty())
We should not mix JUnit and Hamcrest assertions

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-base/src/main/kotlin/com/linkedplanet/kotlininsightclient/InsightSchemaOperatorTest.kt
> +        assertThat(retrievedSchema.objectTypeCount,  greaterThanOrEqualTo (7)) // 7 when test was written
Please extract those IDs into the model

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-sdk/pom.xml
> +                                <input message="ATTENTION!${line.separator}Remove the license information which is stored in the database. Therefore stop Jira, connect to the database (e.g. with Inte
Ensure your test-resources don't contain license information

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-sdk/src/main/kotlin/com/linkedplanet/plugin/jira/insightclient/test/api/PluginComponent.kt
> +package com.linkedplanet.plugin.jira.insightclient.test.api
incorrect package

2023-05-16 09:28 UTC, sjahreis commented on kotlin-jira-client/kotlin-jira-client-test-base/src/main/kotlin/com/linkedplanet/kotlinjiraclient/util/JiraUserTestHelper.kt
>              assertTrue(jiraUser.avatarUrl!!.startsWith("https://www.gravatar.com/avatar"))
Mixture of Hamcrest and JUnit assertions

2023-05-16 09:28 UTC, sjahreis commented on kotlin-http-client/kotlin-http-client-ktor/src/main/kotlin/com/linkedplanet/kotlinhttpclient/ktor/KtorHttpClient.kt
> +            requestBuilder.setBody(bodyIn)
Please help, what was the reason for the "old" comment? I can't remember...

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/experimental/GenericInsightObjectOperatorImpl.kt
> +                InsightObjectAttributeType.REFERENCE -> {
Add USER case?

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/experimental/GenericInsightObjectOperatorImpl.kt
> +    var objectTypeSchema: ObjectTypeSchema
private?

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/experimental/GenericInsightObjectOperatorImpl.kt
> +        val insightObject = insightObjectForDomainObject(objectTypeSchema.id, domainObject).bind() ?: return@either
why do we request the object before deletion? isn't that obsolete?

2023-05-16 09:28 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/experimental/GenericInsightObjectOperatorImpl.kt
> +    companion object {
We should change those to object attributes

2023-05-16 09:30 UTC, sjahreis commented
- [ ] Add a README entry for the kotlin-insight-client and its' submodules

2023-05-23 08:21 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/experimental/GenericInsightObjectOperatorImpl.kt
> +                InsightObjectAttributeType.REFERENCE -> {
Its still experimental. Lets not add more work right now.

2023-05-23 08:22 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/experimental/GenericInsightObjectOperatorImpl.kt
> +    companion object {
I agree, there is a comment for that already inside the class.

2023-05-23 08:25 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/experimental/GenericInsightObjectOperatorImpl.kt
> +    var objectTypeSchema: ObjectTypeSchema
this is public, so clients could use it to add missing functionality

2023-05-23 14:55 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/HttpInsightObjectOperator.kt
>          val objectSelf = "${context.baseUrl}/secure/insight/assets/${this.objectKey}"
callable reicht nicht, weil bei der login Seite auch 200 zurück kommt :D

2023-05-23 14:57 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/model/InsightObjectExtensions.kt
habs mir aufgeschrieben für anderen branch

2023-05-23 14:58 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/model/InsightObjectTypeRestApiResponseObjects.kt
> +    // hidden: Boolean
ist schon gut, dass man sieht, dass da noch mehr zurück kommt

2023-05-23 16:06 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/model/HttpEditModel.kt
> +            if (insightAttr.attributeType == InsightObjectAttributeType.REFERENCE) {
different branch

2023-05-24 12:56 UTC, merged