Feature/generic parser for insight object
linked-planet/kotlin-atlassian-client pull request #2
Opened 2023-05-11 09:27 UTC by HighKo

adds a mapper to all InsightObjectOperator functions to be consistent with the jira issue API

2023-05-22 07:05 UTC, sjahreis requested changes
See the comments

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/impl/AbstractInsightObjectOperator.kt
> +abstract class AbstractInsightObjectOperator<DomainType> : GenericInsightObjectOperator<DomainType> {
Move to package experimental and mark as experimental explicitly?

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/impl/AbstractInsightObjectOperator.kt
> +    private fun createEmptyObject(objectTypeId: InsightObjectTypeId): InsightObject {
Not used

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/impl/AbstractInsightObjectOperator.kt
> +
You yould provide a superclass for your `GenericInsightObjectOperator` and `AbstractInsightObjectOperator` and maybe rename `GenericInsightObjectOperator` to `ReflectiveInsightObjectOperator`?

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/interfaces/InsightObjectOperator.kt
> +        objectTypeId: InsightObjectTypeId, name: String,
name in new line plz

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/interfaces/InsightObjectOperator.kt
>      suspend fun updateObject(obj: InsightObject): Either<InsightClientError, InsightObject>
Return T instead of InsightObject?

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/interfaces/InsightObjectOperator.kt
> +    suspend fun updateObject(obj: InsightObject, vararg insightAttributes: InsightAttribute): Either<InsightClientError, InsightObject>
Return T instead of InsightObject?

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/interfaces/InsightObjectOperator.kt
>      suspend fun createObject(
Return object directly?

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/model/Model.kt
> +            )
Maybe add a toUser function

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-http/src/main/kotlin/com/linkedplanet/kotlininsightclient/http/HttpInsightObjectOperator.kt
> +        return getObjectsByIQL(iql, pageIndex = 0, pageSize = Int.MAX_VALUE, toDomain).map { it.objects }
Int.MAX_VALUE clashes with RESULTS_PER_PAGE - maybe delete the latter?

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectOperator.kt
> +        return getObjectsByIQL(iql, 0, Int.MAX_VALUE, toDomain).map { it.objects }
Int.MAX_VALUE vs. RESULTS_PER_PAGE

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectOperator.kt
> +                "InsightObject create failed.",
Extract errors in API and use them in HTTP and SDK.

Please check if there are more...

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-base/src/main/kotlin/com/linkedplanet/kotlininsightclient/CompanyTestOperatorManualImpl.kt
> +    override suspend fun getByName(name: String): Either<InsightClientError, Company?> =
It should be possible to override the ::identity calls in the super class to prevent overloading all methods

2023-05-22 07:05 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-test-base/src/main/kotlin/com/linkedplanet/kotlininsightclient/CountryTestOperatorManualImpl.kt
> +class CountryTestOperatorManualImpl(private val insightObjectOperator: InsightObjectOperator) : GenericInsightObjectOperator<Country>{
See comments in CompanyTestOperatorManualImpl

2023-05-22 13:57 UTC, sjahreis commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/interfaces/InsightObjectOperator.kt
>      suspend fun updateObject(obj: InsightObject): Either<InsightClientError, InsightObject>
Avoid overloading methods with different return types (see createObject as well)

2023-05-24 12:33 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-sdk/src/main/kotlin/com/linkedplanet/kotlininsightclient/sdk/SdkInsightObjectOperator.kt
> +                "InsightObject create failed.",
will do in different branch

2023-05-24 12:34 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/interfaces/InsightObjectOperator.kt
> +    suspend fun updateObject(obj: InsightObject, vararg insightAttributes: InsightAttribute): Either<InsightClientError, InsightObject>
method is private in newer branch already

2023-05-24 12:35 UTC, HighKo commented on kotlin-insight-client/kotlin-insight-client-api/src/main/kotlin/com/linkedplanet/kotlininsightclient/api/model/Model.kt
> +            )
will do in future branch

2023-05-24 14:17 UTC, merged